### ISSUE TITLE
Standardized way to organize custom field resolver

### ISSUE THREAD

**Issue by pyrou** [nuwave/lighthouse#2188] opened 2022-08-03 14:01 UTC
**What problem does this feature proposal attempt to solve?**

Propose, and document a standardized way to organize custom field resolver in a Laravel project.

**Which possible solutions should be considered?**

Idea is about making the `resolver` attribute optional in the `@field` directive.  

When resolver attribute not provided on `@field` directive, resolver classname/method would be computed from following :

  - The configured namespace in `config(‘lighthouse.namespaces.types’)` 
  - The parent type name 
  - The field name  
 
Example

```graphql
  type User {
  gravatar: String! @field
}
```

 becomes equivalent as  :

```graphql
  type User {
  gravatar: String! @field(resolver: "App\\GraphQL\\Types\\UserType@gravatar")
}
```

  by convention.

**Implementation detail**
  
    Possibly some user would prefer to have something even more fine-grained like, why not a dedicated class per resolver, let's say `App\\GraphQL\\Resolvers\\User\\GravatarResolver@__invoke`. 
    
    To still permit this, the « default resolver name resolver » (yeah.. a proper name has to be found) would be written in a way it could be customized/overridden in project-land (like an app()->bind in a service provider). Then up to the developer to write his own logic of default resolver name resolution. 
    
    **Backward compatibility / Breaking changes**
    
    Currently, resolver attribute is required on `@field` directive. So proposed file organization adoption is optional, and 100% backward compatible with existing lighthouse integration.
    
     I would be happy to contrib to this feature.

**Comment by spawnia** [comment] 2022-08-03 14:11
I am a big fan of having one class per resolver, it makes dependency injection very elegant.

**Comment by pyrou** [comment] 2022-08-03 14:27
I am big fan too, that's why I already proposed a way to do it so.

But as reading documentation I thought you (as nuwave company) would be more happy with one class per Type as default. Because of this documented example : 

```graphql
type User {
  created_at: String!
    @field(resolver: "App\\GraphQL\\Types\\UserType@created_at")
}
```

**Comment by k0ka** [comment] 2022-08-03 14:53
I guess we might just change the default resolver and omit `@field` at all. 

Here is how I did on my project:
1. Simple fields are store in objects. However I'm using Doctrine ORM and I can't use object properties. I've changed the default resolver so it  executes `getProperty()` functions.
2. Complicated fields are handled by one class per resolver.

**Comment by pyrou** [comment] 2022-08-03 15:12
Love the idea about default resolver. 

But, I also had in my drafts a proposition to automatically fallback on snake case when attribute doesn't exists in GraphQL schema case. Because in real life situation, my GraphQL is 100% camelCase, and Laravel still "forces" me to have snake_case in database :(

Then instead of doing this :

```graphql
type User {
   id: ID!
   firstName: String @rename(attribute: "first_name")
   lastName: String @rename(attribute: "last_name")
   avatarUrl: String @rename(attribute: "avatar_url")
}
```

I would love to simply write :

```graphql
type User {
   id: ID!
   firstName: String
   lastName: String
   avatarUrl: String
}
```

Maybe that all together might become a bit too much "magic" ?

**Comment by spawnia** [comment] 2022-08-04 07:52
I have entertained the idea of changing the default resolver for a while, let's track that in a separate issue: https://github.com/nuwave/lighthouse/issues/2191

I have also realized this issue is a duplicate of https://github.com/nuwave/lighthouse/issues/1711.

**Closed** 2022-08-04 07:55 UTC
Labels: duplicate, discussion
