### ISSUE TITLE
Can I register multiple schema files in config/lighthouse.php

### ISSUE THREAD

**Issue by Sithu-Soe** [nuwave/lighthouse#990] opened 2019-10-05 09:32 UTC
**Can I register multiple schema files in config/lighthouse.php**

in config/lighthouse.php

    'schema' => [
        'register' => base_path('graphql/schema.graphql'),
    ],

**Comment by spawnia** [comment] 2019-10-06 13:16
Duplicate of #991

**Closed by spawnia** 2019-10-06 13:16 UTC
