### ISSUE TITLE
Error: Schema must contain named types...

### ISSUE THREAD

**Issue by enzonotario** [nuwave/lighthouse#170] opened 2018-06-27 14:10 UTC
Hi folks! Firstly, thanks so much for this excelent library!

Recently I'm having troubles with newest updates. For example, if I have two `@hasMany`:

```
type Job {
    id: ID!,

    tasks: [Task!]
        @hasMany(type: "paginator", relation: "tasks")

    users: [User!]
        @hasMany(type: "paginator", relation: "users")
}
```

it throws:
`Schema must contain unique named types but contains multiple types named "Job" (see http://webonyx.github.io/graphql-php/type-system/#type-registry).`

Can anyone help me, please?

Thanks in advance!

**Comment by chrissm79** [comment] 2018-06-27 14:21
Hey @enzonotario, I'm assuming it's elsewhere inside your schema, but just to be sure can you copy paste your schema here? The `Job` type you have looks just fine so it has to be somewhere else.

**Comment by enzonotario** [comment] 2018-06-27 14:30
I have deleted/commented everything and leave just that schema, the error persists.

Anyway, I also have cloned your lighthouse-example, and, using `nuwave/lighthouse: "dev-master"` in composer.json, and with a schema like:
```
type Job {
  title: String!
  tasks: [Task!]! @hasMany(type: "paginator")
  users: [User!]! @hasMany(type: "paginator")
}
```

It throws that exception.

Can you, PLEASE, put two `@hasMany` directives in a same Type in your example? I'm sure you will see that exception. 

thanks!!

**Comment by chrissm79** [comment] 2018-06-27 14:58
@enzonotario I bet it's because the repo is still using `dev-master` instead of `v2.0` or `v2.1-rc1`... when i have a moment I'll check out that repo and make the necessary updates. I'm using `dev-master` and i'm not having any issues and I have ~10 types that have multiple `@hasMany` so I'm sure that's what the problem is. I'll update here after I check it out.

**Comment by enzonotario** [comment] 2018-06-27 15:02
I have `dev-master` in my own project.. I just check it in your example to be sure that is not a problem of my project...

Sorry for my ignorance but I don't have to use `dev-master`? I wan't to have the latests updates

**Comment by chrissm79** [comment] 2018-06-27 15:06
You probably don't want to use `dev-master` in your own project... breaking changes are being added to it and there are times when a PR gets merged that will cause tests to fail (thus breaking things elsewhere). 

To play it safe you'll want to use either `v2.0.5` or `v2.1-rc`. If you still want to use `dev-master` you'll need to keep up with the updates and breaking changes until we release `v2.2`.

**Comment by enzonotario** [comment] 2018-06-27 15:19
Ok, I was using it with non errors until I changed to `dev-master`. Now I'm reverted that.

Thanks so much and I will be waiting for new updates!

**Comment by chrissm79** [comment] 2018-06-27 15:20
@enzonotario sounds great! Working on the docs this week so hopefully we'll get `v2.1` cut soon and get the docs site updated!

**Comment by spawnia** [comment] 2018-06-27 17:45
I could replicate that issue, just fleshing out an additional test for it and working on a fix!

**Comment by chrissm79** [comment] 2018-06-27 17:52
@spawnia Interesting, nice find!! @enzonotario thanks for reporting!!!

**Comment by enzonotario** [comment] 2018-06-27 18:11
In fact, I have made a little directive that wraps `PaginateDirective`, and it is to return a collection, without pagination, but inside a `data`. So I don't think that the problem is related just for use `type: "paginator"`, but I also don't understand so much the core concepts of graphql and this library, I just wrap the `PaginateDirective`, removed `paginatorInfor` and force to return a collection instead of a `LengthAwarePaginator`.

I'm sure that the problem is when the directive does:
```
$current->setDefinition($paginatorType);
$current->setDefinition($parentType);
```

But I event don't know what that implies. I'd like to help but I don't even speak english so it is so hard for me...

**Comment by chrissm79** [comment] 2018-06-27 22:08
Okay, if you're on the master branch you should be able to pull down the latest changes which should fix the issue. Please let me know if it's working for you or if you're still experiencing the same issue. Thanks for reporting!!

**Comment by urjathakkar** [comment] 2018-06-27 22:46
I am really new to using Laravel + GraphQL, I have my project set up with basic queries running, can you please guide me to query by id/title field I mean something like a where clause with equals or like. Thanks for all the help and support, managed till here with all your documentation and videos for Lighthouse V2

**Comment by enzonotario** [comment] 2018-06-27 23:16
@chrissm79 yes, it works! thanks so much!!

**Closed** 2018-06-28 02:15 UTC
