### ISSUE TITLE
@restore truncating the global ID for the returned data

### ISSUE THREAD

**Issue by rabrowne85** [nuwave/lighthouse#1838] opened 2021-05-05 15:16 UTC
**Describe the bug**

When a model has the `@softDeletes` directive set and you attempt to `restore` the model as follows:

```gql
mutation restore ($id: ID!) {
    restoreModel (id: $id) {
        id
        deleted_at
    }
}
```

The returned data package is truncating the last 4 characters of the `id`.

This means that whilst the mutation was successful (confirmed that the data in the DB is being correctly changed), the apollo cache is unable to update itself because the `id` does not exist.

**Expected behavior/Solution**

The restore mutation should return the full global id for the item, and not truncate the last 4 characters.

**Steps to reproduce**

1. Run a delete mutation:
```gql
mutation delete ($id: ID!) {
    deleteModel (id: $id) {
        id
        deleted_at
    }
}
```
2. Run a restore mutation for the same ID:
```gql
mutation restore ($id: ID!) {
    restoreModel (id: $id) {
        id
        deleted_at
    }
}
```

**Lighthouse Version**
v5.6.0

**Comment by rabrowne85** [comment] 2021-05-05 15:46
Sorry all, this seems to be an issue with my `schema` file.

I originally had:

```gql
restoreModel(id: ID! @globalId @rules(apply: ["required"])): Model
        @restore(model: "App\\Models\\Model")
```

When I should have had:
```gql
restoreModel(id: ID! @rules(apply: ["required"])): Model
        @restore(globalId: true, model: "App\\Models\\Model")
```

Think there's a statement in the documentation about the `globalId: true` being deprecated, and you should use the `@globalId` variant in V6+. I clearly took this as being that both methods work in v5, but I guess this is incorrect - perhaps someone else can confirm this?

**Comment by spawnia** [comment] 2021-05-05 17:00
The `@globalId` variant should work, I am looking into this.

**Comment by rabrowne85** [comment] 2021-05-06 08:52
@spawnia thanks for looking into this.

The issue is the same if you use the `@globalId` on a delete mutation too. I originally had the delete with the `globalId: true` defined and the restore with the `@globalId`.

i.e.

```gql
deleteSomeModel(
    id: ID! @globalId @rules(apply: ["required"])
): SomeModel @delete(model: "App\\Models\\Some\\Model")
```

When you run the mutation as follows:
```gql
mutation delete ($id: ID!) {
    deleteSomeModel (id: $id) {
        id
        deleted_at
    }
}
```

It drops the last 4 characters of the returned ID too. I assume this is because the directive is the same and that's where the issue is. Either that or it's to do with the mutation code - those seem to be the only two common parts.

To confirm my `type` definition looks like this:

```gql
type SomeModel @node(model: "App\\Models\\Some\\Model") {
    id: ID! @globalId
    _id: ID! @rename(attribute: "id")
    telephone: String
    parent: MyParent! @belongsTo
    address: Address! @hasOne
    created_at: DateTimeUtc!
    updated_at: DateTimeUtc!
    deleted_at: DateTimeUtc
}
```

Just in case it's something in the definition of the schema.

Let me know if you need any more information from me on this one - happy to help.

**Comment by spawnia** [comment] 2023-02-05 17:54
Closing due to lack of a reproducible test case. Feel free to add a pull request that adds a missing test.

**Closed by spawnia** 2023-02-05 17:54 UTC
Labels: bug
