### ISSUE TITLE
Unknown directive

### ISSUE THREAD

**Issue by Danil005** [nuwave/lighthouse#1866] opened 2021-05-30 07:38 UTC
Directives are not displayed in the schema.
I have already tried many options, IDE simply refuses to see them.

I used the command: `php artisan lighthouse:ide-helper`

She created everything, but also keeps giving an error:
![image](https://user-images.githubusercontent.com/26440814/120096197-b8ed0a00-c132-11eb-96bb-486409e6c765.png)

Windows 10, OpenServer

Also i have error:
![image](https://user-images.githubusercontent.com/26440814/120096324-72e47600-c133-11eb-828b-ce668cdaf19a.png)

**Comment by lorado** [comment] 2021-05-30 07:48
As far as I know it is still the problem of `repeatable` keyword, read more here: https://github.com/nuwave/lighthouse/issues/1661#issuecomment-759607196
Here is a workaround for now: https://github.com/nuwave/lighthouse/issues/1661#issuecomment-759715155

I close this, as it seems to be the duplicate of #1661

**Closed by lorado** 2021-05-30 07:48 UTC

**Comment by Danil005** [comment] 2021-05-30 08:05
I found a solution that worked for me! 
[#371 (comment)](https://github.com/nuwave/lighthouse/issues/371#issuecomment-795321022)
