### ISSUE TITLE
How to return array in query and mutation

### ISSUE THREAD

**Issue by Passupphp** [nuwave/lighthouse#2167] opened 2022-06-17 07:33 UTC
Hello,

Please let me know guys, how can i give the images array result on my return.

Query
type GetAllProducts{
id: ID!
title: String
description: String
userId: Int
featured: Int
isFree: Boolean
isBlocked: Boolean
instantBuy: Boolean
groupsId: String
}

Expected Result
"data": {
"getAllProducts": [
{
"id": "10112",
"images": [
"https://res.cloudinary.com/deonpjx2g/image/upload/v1655384211/fileStorage/uploads/products/10112/i9gngghwzzmy9gthckxy.png"
],
"featured": null,
"userId": 10018,
"isFree": true,
"instantBuy": false,
"isBlocked": false,
"title": "etgre",
"description": "ete",
"groupsId": null
},

**Comment by spawnia** [comment] 2022-06-17 07:40
Duplicate of https://github.com/nuwave/lighthouse/issues/2166, stop spamming.

**Closed by spawnia** 2022-06-17 07:40 UTC
