### ISSUE TITLE
@inject for array inputs

### ISSUE THREAD

**Issue by alireza-a2f** [nuwave/lighthouse#1879] opened 2021-06-19 07:46 UTC
Now you can only use `@inject` for simple value injections, but it could be very useful if we were able to use `@inject` for injecting same value into array inputs.

**Inputs:**

```graphql
input ActivityInput {
  id: ID
  goal: String
}

input ActivityRelationInput {
  upsert: [ActivityInput]
  delete: [ID]
}

input CustomerInput {
  id: ID
  name: String
  activities: ActivityRelationInput
}
```

**Mutation:**

```graphql
extend type Mutation {
  customerUpsert(input: CustomerInput! @spread): Customer
  @upsert(model: "App\\Models\\Customer")
  @inject(context: "user.id" name: "activities.upsert[].user_id")
}
```

**Comment by spawnia** [comment] 2021-06-21 07:17
This functionality would have to be implemented here: https://github.com/nuwave/lighthouse/blob/0d8f0fb8a3dd2791dda4c772f3db4b53ee072fb3/src/Execution/Arguments/ArgumentSet.php#L239.

The syntax should probably be the same as in array validation: `activities.upsert.*.user_id`.

What is supposed to happen when the client does not pass nested inputs down to that level?

**Comment by wilsonwg** [comment] 2021-07-27 06:57
It would be great if this functionality is available, because I would like to inject user_id in the nested mutation.

**Comment by heyddi** [comment] 2022-08-15 09:14
Hi there! 

I am just starting with Laravel and Lighthouse so I still have a long way to go... I am trying to work on the `addValue` to handle the wildcard but for now I am completely stuck :( Any chance I missed a PR somewhere (something not committed maybe) that could help or point in the right direction?

Thanks!

Ed

**Comment by spawnia** [comment] 2023-02-05 17:50
Duplicate of https://github.com/nuwave/lighthouse/issues/1206.

**Closed by spawnia** 2023-02-05 17:50 UTC
Labels: enhancement
