### ISSUE TITLE
Confusion using @orderBy directive

### ISSUE THREAD

**Issue by IgorDePaula** [nuwave/lighthouse#967] opened 2019-09-18 15:35 UTC
I'm trying using @orderBy directive, I receive this message:

Variable "$orderBy" of type "[OrderByClause]" used in position expecting type "[OrderByClause!]".

**Steps to reproduce**

My query is: 

```
donatorsByString2(count: Int!, page: Int!,payment_form_id: [Int] @in(key:"payment_form_id"), donator_status_id: [Int]  @in(key:"donator_status_id"), donator_type_id: [Int]  @in(key:"donator_type_id"), shipping_method_id: [Int]  @in(key:"shipping_method_id"), search_full_name: String @where(operator: "like",clause:"orWhere", key: "full_name"), search_document: String @where(operator: "like", clause:"orWhere", key: "document"), search_email: String @where(operator: "like", clause:"orWhere", key: "email"), orderBy: [OrderByClause!] @orderBy): [User!]! @middleware(checks: ["auth:api"]) @paginate(scopes:["donator"])
```
In apollo client:

```
quyery:...,
variables() {
                        return {
                            'page': props.pagination.page || 1,
                            'count': props.pagination.rowsPerPage || 3,
                            'payment_form_id': this.formaPagamento,
                            'donator_status_id': this.statusDoador,
                            'donator_type_id': this.tipoDoador,
                            'shipping_method_id': this.formaEnvio,
                            'filter': `%${this.filter}%`,
                            orderBy:{field:'full_name','order':'ASC'}
                        }
                    },
```

I tried:

 orderBy:[{field:'full_name','order':'ASC'}]

 orderBy:{field:'full_name','order':'ASC'}

 orderBy:['full_name','ASC']

and I receive always the same message: Variable "$orderBy" of type "[OrderByClause]" used in position expecting type "[OrderByClause!]".

The doc is confusing about this topic.

**Output/Logs**

<details><summary>Click to expand</summary>

```
Variable "$orderBy" of type "[OrderByClause]" used in position expecting type "[OrderByClause!]".
```

</details></br>

**Environment**

Lighthouse Version: 3.7
Laravel Version: 5.8

**Comment by enzonotario** [comment] 2019-09-18 16:00
Please, follow the issue templates. Make questions in StackOverflow/Slack.

Btw, I'm sure the problem is in the definition of the query in the apollo client side. Just be sure to add the `!`.

**Comment by IgorDePaula** [comment] 2019-09-18 16:40
1- I followed the templates.
2- You have serious problems with me, any issue opened by me are closed without investigation. =/ 

I'm almost desist from this and back to restful.

**Comment by enzonotario** [comment] 2019-09-18 16:51
Yes sorry, my bad about the issue template. However I dont see the name of who open an issue.
I can help you if you show me the code of the query in the apollo client side.
Have you tried adding the ‘!’ ?

**Comment by IgorDePaula** [comment] 2019-09-18 16:54
Thank you very much

**Comment by spawnia** [comment] 2019-09-18 17:19
What leads you to believe that this is a problem within Lighthouse?

**Comment by spawnia** [comment] 2019-09-21 17:41
@IgorDePaula i am going to close this issue, as the error message is quite clear and i don't see anything wrong with Lighthouse.

Before opening further issues, consider if what you are experiencing is actually a problem rooted within Lighthouse. You can dig into the code yourself if necessary. Our time is limited and i would like to focus on actual problems and not support questions.

**Closed by spawnia** 2019-09-21 17:41 UTC
Labels: question

**Comment by IgorDePaula** [comment] 2019-09-21 19:59
@spawnia great, if you don't like response the questions, close the repo for issues. I see many people mistreating or being rude to brazilians. 

Do you know how many times you called me a donkey indirectly?

You Said that your package is perfect, that the problem is me. You is perfect, ok, I will look another package, from a mortal, not from a God.

**Comment by webard** [comment] 2019-09-21 20:27
GraphQL is not simple and requires a lot of knowledge outside of this package. It is problem with definition of variabled in your query, not their values, and this is not a problem with this package, but your use of it. Issues are not used to solve such problems.

**Comment by spawnia** [comment] 2019-09-22 12:03
This package is built and maintained through volunteer effort. The issue tracker is meant for collaboration to find bugs or improve features. It is not a place to ask questions about the usage or demand free support. When you struggle with a particular issue, you can ask for help in Slack or on StackOverflow.

What have you done to improve this package and make it easier to work with? You are free to contribute bug fixes or documentation.

**Comment by IgorDePaula** [comment] 2019-09-22 13:56
I report a bug, not free support. I develop from 10 year ago. I know read source code. And more time you said that I'm donkey again. This is rude. Close the issues tool if you not want help your users.

**Comment by enzonotario** [comment] 2019-09-22 14:04
Hey Igor, please come to our [Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWI1ZDQ1YWM1NmM2MmQ0NTU0NGNjZWFkMTJhY2VjMDAwZmMyZDFlZTc1Mjc3ZGY0MWM1Y2Q5MWNjYmJmYWJkYmU).
I'm more than happy to help you. Please let this discussion that doesn't give us anything positive.
And sorry again for my mistake.

**Comment by IgorDePaula** [comment] 2019-09-22 14:11
You only confirm all tha I said. Thank you.

**Comment by spawnia** [comment] 2019-09-22 14:12
By now, three people have said that what you are experiencing is not a bug.

If you are still convinced that this is indeed a bug, you can fix it and open a PR.

**Comment by enzonotario** [comment] 2019-09-22 14:13
No. It is not a bug. It's just a question. And I'm sure that the solution is what I said in the first comment.

**Comment by marcondesdddi** [comment] 2019-10-15 16:14
I have the same problem as him, could anyone help?

`import gql from 'graphql-tag'

export const GET_USERS_PAGINATION = (quant, pagePagination, orderBy) => {

    quant = quant || 10;
    pagePagination = pagePagination || 1;
    orderBy = orderBy || {
        field: "name",
        order: `ASC`
    }

    console.log(orderBy)

    return gql `{
        users(first: ${quant}, page: ${pagePagination}, orderBy: [${orderBy}]) {
            paginatorInfo {
                count,
                currentPage,
                firstItem,
                hasMorePages,
                lastItem,
                lastPage,
                perPage,
                total
            }
            data {
                id,
                name,
                username,
                email
            }
        }
    }`

}
`

**Comment by enzonotario** [comment] 2019-10-15 18:53
Sure! I'm sure you are also missing the `!`. I can help you a bit more in our [Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

**Comment by marcondesdddi** [comment] 2019-10-16 18:37
Thank you so much, IgorDePaula helped me.
