### ISSUE TITLE
Please add the Automatic persisted queries feature to the package 

### ISSUE THREAD

**Issue by Rasool-deldar** [nuwave/lighthouse#1801] opened 2021-04-15 10:02 UTC
**What problem does this feature proposal attempt to solve?**

 reducing request sizes

**Which possible solutions should be considered?**

Hello . Please add a feature to Automatic persisted queries This feature is very useful

[Automatic persisted queries](https://www.apollographql.com/docs/apollo-server/performance/apq/)

**Comment by spawnia** [comment] 2021-04-16 10:04
Duplicate of https://github.com/nuwave/lighthouse/issues/651

**Closed by spawnia** 2021-04-16 10:04 UTC

**Comment by Rasool-deldar** [comment] 2021-04-16 17:11
D
