### ISSUE TITLE
Validator directive is getting executed before auth

### ISSUE THREAD

**Issue by ayech0x2** [nuwave/lighthouse#2203] opened 2022-09-07 13:57 UTC
Here my schema. 

`
createOrder(reference: String products:
  [OrderProduct]! client_id: ID ): Order 
@guard(with: ["user"]) 
@validator(class: "CreateOrderValidator") 
@field(resolver: "OrderMutator@createOrder")
`

The Guard directive is supposed to be a middleware, isn't it? It must therefore be executed before validation!

Thanks for the package by the way.

**Comment by spawnia** [comment] 2022-09-07 19:20
Duplicate of https://github.com/nuwave/lighthouse/issues/1780

**Closed by spawnia** 2022-09-07 19:20 UTC
