### ISSUE TITLE
Type/Field descriptions

### ISSUE THREAD

**Issue by robsontenorio** [nuwave/lighthouse#340] opened 2018-09-20 01:11 UTC
**Describe the bug**

Type/Field descriptions not showing

**Expected behavior**

Generated docs should display properly

**Schema**

```graphql
"""
This is a description for player type
"""
type Player{
  id: ID!  
  """This is a description for nickname field"""
  nickname: String!  
}
```
**Environment**

Lighthouse Version: 2.2
Laravel Version: 5.7
PHP Version: 7.2

**Additional context**
Is it a LightHouse , laravel-graphql-playground or graphql-playground bug? Player type description and nickname field descriptions are not showing.

![captura de tela 2018-09-19 as 22 09 39](https://user-images.githubusercontent.com/118955/45789999-14179080-bc59-11e8-8eaa-67b34f3472ee.png)

**Comment by mfn** [comment] 2018-09-20 05:07
Duplicate of https://github.com/nuwave/lighthouse/issues/297

**Closed** 2018-09-20 05:52 UTC
