### ISSUE TITLE
`@bcrypt` won't work with input object field

### ISSUE THREAD

**Issue by yaquawa** [nuwave/lighthouse#375] opened 2018-10-10 09:03 UTC
**Describe the bug**

`@bcrypt` won't work when:

```graphql
type Mutation {
    foo(bar: BarInput): Foo @field(resolver: "FooResolver@resolve")
}

input BarInput {
    password: String! @bcrypt
}
```

```php
class FooResolver
{
    public function resolve($root, $args)
    {
        // `$args['password']` was not been encoded 
    }
}
```

**Comment by spawnia** [comment] 2018-10-10 09:05
Duplicate of #372

**Closed by spawnia** 2018-10-10 09:05 UTC
