### ISSUE TITLE
Throttling headers like Retry-After are not included in response

### ISSUE THREAD

**Issue by Stevemoretz** [nuwave/lighthouse#2309] opened 2023-02-19 15:19 UTC
**Describe the bug**

Laravel adds a few headers for handling throttling, lighthouse isn't sending them on the response.

**Expected behavior/Solution**

It should pass those headers.

**Steps to reproduce**

1. go to `wp-/app/Providers/RouteServiceProvider.php`
2. set limit to a low value : `Limit::perMinute(1)`
3. send 2 requests the second one will throw the throttle error with no `Retry-After` in its response headers.

The workaround is this which I found accidentally at https://github.com/laravel/framework/issues/34534#issuecomment-698860989

```php
        RateLimiter::for("api", function (Request $request) {
            return Limit::perMinute(1)
                ->by(optional($request->user())->id ?: $request->ip())
                ->response(function ($request, $headers) {
                    return new JsonResponse(
                        [
                            "errors" => [
                                "message" => "Too many request..."
                            ],
                        ],
                        429,
                        $headers
                    );
                });
        });
```

And the problem doesn't seem to be from Laravel just lighthouse:
https://github.com/laravel/framework/issues/34534#issuecomment-1436008792

**Output/Logs**

<details><summary>Click to expand</summary>

```
No errors in output.
```

</details></br>

**Lighthouse Version** : Master Branch

**Comment by spawnia** [comment] 2023-02-19 19:15
First step towards a fix is a failing test case. It is not clear to me what exactly the problem is, and I do not know how to fix it. Open for pull requests.

**Comment by Stevemoretz** [comment] 2023-02-19 19:18
> First step towards a fix is a failing test case. It is not clear to me what exactly the problem is, and I do not know how to fix it. Open for pull requests.

Hello Benedikt, I would have provided the PR but I'm a little busy these days.
Though I definitely can explain it better if I were vague.

**Comment by spawnia** [comment] 2023-02-19 19:19
I am not planning to work on this myself.

**Comment by Stevemoretz** [comment] 2023-02-19 19:19
Then I might come back to this later when I get some free time

**Comment by spawnia** [comment] 2023-08-09 08:38
Closing due to lack of reproducibility.

**Closed by spawnia** 2023-08-09 08:38 UTC
Labels: needs reproduction
