### ISSUE TITLE
Lacking the `@belongsToMany` directive

### ISSUE THREAD

**Issue by yaquawa** [nuwave/lighthouse#354] opened 2018-10-02 05:05 UTC
We have `@hasOne` `@belongsTo` `@hasMany` directives, the only lost part is the `@belongsToMany`! Hope this can be added as well. Thanks!

**Comment by spawnia** [comment] 2018-10-02 06:17
Duplicate of #332

**Closed by spawnia** 2018-10-02 06:17 UTC

**Comment by yaquawa** [comment] 2018-10-03 12:49
@spawnia Do you have any plans on adding this directive recently? If not, I guess I have to send a PR on this, because I really need this feature right now.

**Comment by spawnia** [comment] 2018-10-03 19:58
Go ahead and give it a shot! Should be pretty straightforward. Make sure to add it to the docs repo as well ☺️
