### ISSUE TITLE
Creating where condition for nested relations

### ISSUE THREAD

**Issue by alexey-krukover** [nuwave/lighthouse#1409] opened 2020-06-07 19:02 UTC
I will gladly provide the necessary changes for this issue

**What problem does this feature proposal attempt to solve?**

Currently the `whereCondition` directive does not support filtering for nested relations

**Which possible solutions should be considered?**

Adding support for relation path with delimiter, that simply checks the provided condition with the Laravel function `whereHas`. Which in my option can be integrated with the `handleWhereConditions` function inside the `whereConditionsBaseDirective` class. In addition, some of the `whereHasConditionsBaseDirective` code can be removed and use the new options of the `whereConditionsBaseDirective` instead. Also to further improve future support. beside the relation path, we can pass an integer to filter out results based on how many items match the `has` condition, which is also natively supported in Laravel.

**Example**
```graphql{
user(
    where: {
       HAS: {
           relation  : 'posts.comments'
           amount    : 3
           operator  : EQ
           condition : {
               column : 'text'
               value  : 'test'
           }
       }
     }) {
    name
  }
}

**Comment by spawnia** [comment] 2020-06-07 20:31
How would the generated input types look like then compared to now: https://lighthouse-php.com/master/eloquent/complex-where-conditions.html#wherehasconditions

What about nesting the `HAS` conditions within other logical operators such as `AND`?

**Comment by Necroblight** [comment] 2020-06-08 11:18
In addition maybe also add property for `operator' to be able to set `has` condition with `equal` or `less than`  comparison conditions.

**Comment by Necroblight** [comment] 2020-06-08 17:41
> What about nesting the `HAS` conditions within other logical operators such as `AND`?

I encountered the conflict of getting relation in builder versus in model. I have some rough ideas how it could be possible to overcome, that I can try out. If the idea itself is fine with you, then the problem itself I'll try to solve in the pull request.

**Comment by Necroblight** [comment] 2020-06-09 07:16
After researching the issue more, I understand your questions better. So here's my revised response;

> How would the generated input types look like then compared to now: https://lighthouse-php.com/master/eloquent/complex-where-conditions.html#wherehasconditions

```graphql
input UsersWhereConditions
{
  column: UsersColumn

  operator: SQLOperator = EQ

  value: Mixed

  AND: [PeopleHasRoleWhereConditions!]

  OR: [PeopleHasRoleWhereConditions!]

  HAS: UsersRelationWhereConditions
}

input UsersRelationWhereConditions
{
  relation: String!

  operator: SQLOperator = GTE

  amount: Int = 1

  condition: PeopleHasRoleWhereConditions
}
```

The only problem is that condition refers to an input that isn't incorrect. In practice it should work as it accepts the exact same parameters. But on the other hand, the introspection won't give the accurate hinting for the `column` parameter when inside the `HAS` scope. Question is, is it something that can can compromised on, or shouldn't be considered unless there's a bulletproof solution?

> What about nesting the `HAS` conditions within other logical operators such as `AND`?

Regarding that issue, I think we can try told reference to the model, and when entering a logical operator scope, we can apply all the further recursive wheres on a clean model, and then combine the resulting wheres with the actual builder. Also when entering a nested `HAS` inside a different `HAS`, we can just get the model of the relation, and then do the same thing I mentioned before.

**Comment by spawnia** [comment] 2020-06-10 07:29
Yeah, there are some tricky bits to solve. I wonder if we use more code generation to create a safer schema for the enduser. We might generate an `enum` for the available relations and use it like:

```graphql
input UsersRelationWhereConditions {
  relation: [UsersRelation!]!
}

enum UsersRelation {
  POSTS
  TASKS
}
```

**Comment by Necroblight** [comment] 2020-06-10 08:17
The `HAS` argument works perfectly right now in all situations, what left is only the generated input.

I also thought of the `enum` idea to create all possible relations (nested included). Which is the ideal solution, and further even gives a nice mapping of all the relations for the client to see. The problem is what comes after that, and it's the fact that in a complex system the amount of relations can get really huge, and in addition alot of relations will loop back to one of the proceeding models. For the looping thing it is possible to set up something that will detect when relation nesting starts to repeat itself, and stop it. We can work on how smart it is and only stop nesting at specific situations for relations that shouldn't be practically used. But even with, we will probably not be able to support 100% of relations, although at worst case, people can just nest relations inside other relations to reach them, which the directive currently supports with the addition of `HAS`. But my other main concern is the performance. Because the amount of relation can get really really big, it might impact performance.

If you think the performance isn't an issue, and the idea is good enough, then tell me and I'll start implementing the idea.

**Comment by Necroblight** [comment] 2020-06-10 08:29
Also I thought to make it like this ;

```graphql
input UsersWhereConditions
{
  column: UsersColumn

  operator: SQLOperator = EQ

  value: Mixed

  AND: [UsersWhereConditions!]

  OR: [UsersWhereConditions!]

  HAS: [UsersRelations!]!
}

enum UsersRelations {
  UsersPostsWhereConditions
}

input UsersPostsWhereConditions
{
  operator: SQLOperator = GTE

  amount: Int = 1

  condition: PostsWhereConditions
}

input PostsWhereConditions
{
  column: UsersColumn

  operator: SQLOperator = EQ

  value: Mixed

  AND: [UsersWhereConditions!]

  OR: [UsersWhereConditions!]

  HAS: [PostsRelations!]!
}
```

**Comment by Necroblight** [comment] 2020-06-10 08:54
I misunderstood what you were referring to, and just realized you were referring to just strings of all possible relations. for some reason I thought GraphQL would support multiple possible inputs on property using `enum`, so what I talked about in this reply, and later in the example, is for a way to support complete interpolation for relation conditions.

Which  brings me to a question, is it even feasible in GraphQL to allow different inputs on one property?

**Comment by Necroblight** [comment] 2020-06-10 09:12
I also thought of the `enum` idea to create all possible relations (nested included). Which is the ideal solution, and further even gives a nice mapping of all the relations for the client to see. The problem is what comes after that, and it's the fact that in a complex system the amount of relations can get really huge, and in addition alot of relations will loop back to one of the proceeding models. For the looping thing it is possible to set up something that will detect when relation nesting starts to repeat itself, and stop it. We can work on how smart it is and only stop nesting at specific situations for relations that shouldn't be practically used. But even with that, there would still be blind spots, and with it being an `enum` it would completely restrict the user from accessing the relation, which probably is a deal breaker in this situation

But I had another idea; it is to create additional input for all possible relations, in which way we will be able to accesses the where directive of all their relations, and even use as a proxy to access further depth of relations that you otherwise wouldn't be able to access with just `enum`. But the main drawback, and my concern, is the possible impact on the performance because as I said earlier, some databases can have unimaginable number of relations.
In addition , instead of the `relation` parameter, it should just take the name of the `enum` and parse into the actual path of the relation, so the naming should be really strict.

**example**
```graphql
input UsersWhereConditions
{
  column: UsersColumn

  operator: SQLOperator = EQ

  value: Mixed

  AND: [UsersWhereConditions!]

  OR: [UsersWhereConditions!]

  HAS: UsersRelationConditions 
}

input UsersRelationConditions {
  Posts: UsersPostsHasConditions
  PostsComments: UsersPostsCommentsHasConditions
}

input UsersPostsHasConditions
{
  operator: SQLOperator = GTE

  amount: Int = 1

  condition: PostsWhereConditions
}

input PostsWhereConditions
{
  column: UsersColumn

  operator: SQLOperator = EQ

  value: Mixed

  AND: [UsersWhereConditions!]

  OR: [UsersWhereConditions!]

  HAS: PostsRelationConditions
}
```

**Comment by Necroblight** [comment] 2020-06-10 09:56
And if the performance is an issue, but  idea is good. We can create a setting to limit the depth of the relation the generated input is mapping. And we'll still be able to access any relation, just will have to access it through the nested relations, instead of directly. And it might be good option for the user to set the setting based on the complexity of their database, and the performance they are willing to sacrifice for it.
In addition, the default should probably be just 1, and then in some documentation or something mention that if they want generated input for deeper relations, they should set it to as high as they want, so that users who don't need access to nested relation, or don't need it at all to begin with, won't have to suffer any performance impact at all.
And also, maybe there should be option to set the setting to 0 to just completely disable the option, to be able to save as much performance as possible.

**Comment by Necroblight** [comment] 2020-06-10 11:39
Also I think with what I mentioned above, we can just deprecate the `WhereHasDirective` altogether.

**Comment by spawnia** [comment] 2020-08-05 17:09
https://github.com/nuwave/lighthouse/pull/1412 is merged.

**Closed by spawnia** 2020-08-05 17:09 UTC
Labels: enhancement

**Comment by stephenjason89** [comment] 2021-04-19 06:13
@alexey-krukover 
Good day,
I am trying to use this functionality right now.

**Comment by alexey-krukover** [comment] 2021-04-19 17:59
@stephenjason89 been long since I touched GraphQL, but I think you can just use regular where directive on the relation. It does create a duplicate code as you need to declare same condition on the relation and the root, but that's the straightforward way to do it. I do remember doing it in a more elegant way, but don't remember how exactly.

**Comment by stephenjason89** [comment] 2021-04-20 04:04
@alexey-krukover Thank you for that. That was what i ended up doing. If you happen to remember how to do it elegantly, it would be really nice if you can post it here someday.

Thank you again. :)

**Comment by alexey-krukover** [comment] 2021-04-20 11:59
> @alexey-krukover Thank you for that. That was what i ended up doing. If you happen to remember how to do it elegantly, it would be really nice if you can post it here someday.
> 
> Thank you again. :)

Maybe try removing the condition from the root directive. And then it might check if if anything contained in the relation after filtering it.

**Comment by stephenjason89** [comment] 2021-04-20 17:17
this is what i end up doing,
```
query {
  productsFilter(
    first: 10
    page: 1
    orderBy:[{column:ID order:ASC}]
    where: {
      AND: [
        { HAS: { relation: "inventories.rack.branch", condition: { column: ID, value: 2 } } }
        { HAS: { relation: "inventories.rack", condition: { column: ID, value: 277 } } }
      ]
    }
  ) {
    data {
      id
      item_code
      barcode
      inventories(where: {
      AND: [
        { HAS: { relation: "branch", condition: { column: ID, value: 2 } } }
        { HAS: { relation: "rack", condition: { column: ID, value: 277 } } }
      ]
    }) {
        id
        rack {
          id
          name
          branch {
            id
            name
          }
        }

        qty
      }
    }
    paginatorInfo {
      total
    }
  }
}

```

Could you explain a bit further what you meant on this example?

Thank you

**Comment by alexey-krukover** [comment] 2021-04-20 17:57
Try doing it like that;

```query {
  productsFilter(
    first: 10
    page: 1
    orderBy:[{column:ID order:ASC}]
    where: {
      AND: [
        { HAS: { relation: "inventories.rack" } }
      ]
    }
  ) {
    data {
      id
      item_code
      barcode
      inventories(where: {
      AND: [
        { HAS: { relation: "branch", condition: { column: ID, value: 2 } } }
        { HAS: { relation: "rack", condition: { column: ID, value: 277 } } }
      ]
    }) {
        id
        rack {
          id
          name
          branch {
            id
            name
          }
        }

        qty
      }
    }
    paginatorInfo {
      total
    }
  }
}```

Not sure if it'll work, but worth a try. The idea here is that after the relation is filtered, we do another filtering that filters out anything with empty relation.

**Comment by stephenjason89** [comment] 2021-04-22 05:57
@alexey-krukover 
Thank you for taking the time to help me out.
However, this doesn't seem to work properly

This is the intended result:
![image](https://user-images.githubusercontent.com/3810177/115663106-8c471500-a372-11eb-9311-0734bb36feac.png)


This is the other result:
![image](https://user-images.githubusercontent.com/3810177/115663162-a680f300-a372-11eb-9878-8bc5b458c7c2.png)


Again, thank you for your time, i appreciate it.

**Comment by JonMoreno** [comment] 2021-05-06 20:08
Why is this close? anyone able to figure out nested relationship with where?

**Comment by alexey-krukover** [comment] 2021-05-06 20:37
> Why is this close? anyone able to figure out nested relationship with where?

Check documentation, the PR was created and approved

**Comment by LauJosefsen** [comment] 2022-08-18 21:14
@stephenjason89 
I struggle to find any documentation on how to accomplish this result, even though the issue is closed.

Do you mind sharing what you ended up having in your `type Query` to parse the where argument correctly, or simply what directive you used? Using the regular `@where` directive results in my query trying to perform a query along the lines of:
```sql
select * from `users` where `where` = =
``` 

I can solve my problem partly by using the `whereHas` directive, but I want to avoid adding a new argument for every relation I want to check.

**Comment by stephenjason89** [comment] 2022-09-30 19:34
@LauJosefsen 
I ended up having this on my type Product
<img width="816" alt="image" src="https://user-images.githubusercontent.com/3810177/193343530-a5ff8a3b-936c-4d32-9c3c-ed6b61f0f6d7.png">

This is the method on my Product.php
<img width="696" alt="image" src="https://user-images.githubusercontent.com/3810177/193343607-3c557c7e-22cb-48c3-8d3a-c696e9608b1e.png">

And this is my gql
<img width="799" alt="image" src="https://user-images.githubusercontent.com/3810177/193343691-375ecab0-8b44-4cee-b7f2-27efb9a8415d.png">

I hope it helps
