### ISSUE TITLE
Only one nested belongsTo create fires when more than one is present

### ISSUE THREAD

**Issue by nathangaskin** [nuwave/lighthouse#1213] opened 2020-02-28 08:40 UTC
**Describe the bug**

When a type has multiple belongsTo relationships, and a mutation triggers a create on both of them, only the one that appears first in the schema is fired and the rest are ignored.

I've been able to trace it as far as [SaveModel](https://github.com/nuwave/lighthouse/blob/8a2317e496e92f888fe575b4ed8291bb04a17f36/src/Execution/Arguments/SaveModel.php#L47). The ArgPartitioner finds both of the belongsTo relations fine, but the foreach is only looping once?

**Expected behavior/Solution**

Every belongsTo entity is created when requested

**Steps to reproduce**

Schema:
```
type Mutation {
    createProduct(input: CreateProductInput! @spread): Product @create
}

"TYPES"

type Product {
    id: ID!
    name: String!
    sku: String!

    manufacturer: ProductManufacturer! @belongsTo
    category: ProductCategory! @belongsTo
}

type ProductManufacturer {
    id: ID!
    name: String!
    products: [Product!]! @hasMany
}

type ProductCategory {
    id: ID!
    name: String!
    products: [Product!]! @hasMany
}

"INPUTS"

input CreateProductInput {
    name: String!
    sku: String!
    manufacturer: CreateProductManufacturerRelation!
    category: CreateProductCategoryRelation!
}

input CreateProductManufacturerRelation {
    connect: ID
    create: CreateProductManufacturerInput
}

input CreateProductCategoryRelation {
    connect: ID
    create: CreateProductCategoryInput
}

input CreateProductManufacturerInput {
    name: String!
}

input CreateProductCategoryInput {
    name: String!
}
```

Query:
```
mutation {
  createProduct(input: {
    name:"My amazing product"
    sku:"SKU0001"
    manufacturer: {
      create: {
        name: "Awesome Corp"
      }
    }
    category: {
      create: {
        name: "Doodads"
      }
    }
  }){
    id
  }
}
```

**Output/Logs**

<details><summary>Click to expand</summary>

```
"debugMessage": "SQLSTATE[HY000]: General error: 1364 Field 'category_id' doesn't have a default value (SQL: insert into `products` (`name`, `sku`, `manufacturer_id`) values (My amazing product, SKU0001, 21))"
```

</details></br>

**Environment**

Lighthouse Version: 4.9
Laravel Version: 6.4.1

**Comment by enzonotario** [comment] 2020-03-02 12:50
How is your `Product` model?

**Comment by nathangaskin** [comment] 2020-03-03 12:43
```
class Product extends Model
{
    protected $fillable = [
        'name', 'sku'
    ];

    public function manufacturer(): BelongsTo
    {
        return $this->belongsTo('App\ProductManufacturer', 'manufacturer_id');
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo('App\ProductCategory', 'category_id');
    }
}
```

**Comment by enzonotario** [comment] 2020-03-03 12:47
Try adding `manufacturer_id` and `category_id` to `$fillable`

**Comment by nathangaskin** [comment] 2020-03-03 12:52
That hasn't had any effect unfortunately

**Comment by vitorsemeano** [comment] 2020-04-09 16:06
I also have this problem. But in my case I have a table that have 2 foreign keys (both fields are required and there's no default value). 

I have a mutation to create/update a given resource (upsert). This type have two fields with a belongsTo directive. The mutation is built with an input similar to the type definition, including these two fields with an upsert for each sub type (the ones with a belongsTo directive).

Suppose i call this mutation, to create the given resource, where i also pass these 2 fields, that don't exist in the database. So i expect that lighthouse will create each type for these 2 fields when resolving the field, and then, when all fields are resolved, the given resourcse will also be created in the database. 

What actually happens is that lighthouse fails, giving a query error, that the second field that have a belongsTo, imagine type_id, does not have a default value, meaning, that this second field, that should be resolved, is not present in the query.

For what i found when debugging, this happens during the field resolution of the first belongsTo. It saves the model, and then it checks "if the parent relation is instance of belongs to, then i will associate this model i just created with the parent model, and save it". When this happens, the error occurs, because this additional save that happens in the parent type, the given resource, should not happen when solving the fields of the mutation.

I also tested this theory, changing the order of the fields that have a belongsTo, and i can confirm that the query error still occurs, but claiming that the other foreign key does not have a default value. 

Not sure if i was clear enough, but if you need anything else, just ask. 

Thanks

**Comment by vitorsemeano** [comment] 2020-04-09 16:21
I solve the problem, removing the save(), on line 71, of the file SaveModel.php. Not sure the implications of this. I would prefer your feedback and rectification in this matter.

**Closed** 2020-04-15 14:39 UTC
Labels: bug
