### ISSUE TITLE
null return not being allowed

### ISSUE THREAD

**Issue by souljacker** [nuwave/lighthouse#1032] opened 2019-11-02 02:41 UTC
My schema has

```graphql
type Query {
  me: User
}
```

And my me resolver is returning null if the user is not logging it. But I get this error

```
debugMessage: Cannot return null for non-nullable field User.id.
```

Shouldn't I be allowed to return null in this case?

I was able to circumvent this by creating a a custom type and returning it instead

```graphql
type Query {    
    me: mePayload
}

type mePayload {
    user: User
}
```

This allows me to return null

**Comment by eriktisme** [comment] 2019-11-02 11:29
Can you show us your User model type?

```graphql
type User @model {
    id: ID! <--- is the reason probably
}
```

**Comment by joskfg** [comment] 2019-11-02 13:15
Are you returning null or are you returning a user without data?

**Comment by spawnia** [comment] 2019-11-03 11:22
I think the issue you are having is a combination of what @eriktisme and @joskfg said.

Make sure to return `null` from the `me` field, not an empty User.

Closing as this looks like expected behaviour.

**Closed** 2019-11-03 11:50 UTC
Labels: question
