### ISSUE TITLE
I cannot access to a field twice.

### ISSUE THREAD

**Issue by hosmelq** [nuwave/lighthouse#247] opened 2018-08-07 03:22 UTC
**Describe the bug**
I cannot access to a field twice.

**Schema**

```graphql
type Campaign @model {
  posts: [Post!]! @hasMany(type: "relay")
}

type Post @model {
  campaign: Campaign! @belongsTo
}
```

```graphql
{
  node(id: "Q2FtcGFpZ246MzIy") {
    ... on Campaign {
      _id
      id
      posts(first: 1) {
        edges {
          node {
            _id
            id
            campaign {
              _id
              id
              posts(first: 1) {
                edges {
                  node {
                    _id
                    id
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Output/Logs**

```json
{
  "data": {
    "node": {
      "_id": 322,
      "id": "Q2FtcGFpZ246MzIy",
      "posts": {
        "edges": [
          {
            "node": {
              "_id": 69,
              "id": "UG9zdDo2OQ==",
              "campaign": {
                "_id": 322,
                "id": "Q2FtcGFpZ246MzIy",
                "posts": null
              }
            }
          }
        ]
      }
    }
  }
}
```

**Environment**

Lighthouse Version: 2.2-beta.1
Laravel Version: 5.5
PHP Version: 7.2.7

**Additional context**
As you can see in the output, the latest `posts` field is null, i was looking into this and i found that the problem is read the [value](https://github.com/nuwave/lighthouse/blob/master/src/Support/DataLoader/BatchLoader.php#L59).

I added a log in every run before the return.

```php
logger(array_keys($this->keys[$key]));
```

```php
[
    0 => 'relation',
    1 => 'parent',
    2 => 'args',
    3 => 'scopes',
    4 => 'type',
    5 => 'value',
]
```

```php
[
    0 => 'relation',
    1 => 'parent',
    2 => 'args',
    3 => 'scopes',
    4 => 'type',
]
```

in the second run the value is not set.

**Comment by chrissm79** [comment] 2018-08-07 17:06
@hosmelq Thanks for reporting! I assume it's generating the same key since both fields have the same name... might not be able to debug until this afternoon but I'll update here when I have a fix!

**Comment by chrissm79** [comment] 2018-08-07 17:35
@hosmelq I have a simple fix (#250) I just need to add a test and I'll be able to merge it in. However, I was able to reproduce your issue locally and this change seemed to resolve it.

**Comment by hosmelq** [comment] 2018-08-07 17:45
@chrissm79 I tested locally and this fix the issue.

**Comment by chrissm79** [comment] 2018-08-07 19:34
👍The PR has been merged

**Closed** 2018-08-07 19:34 UTC
