### ISSUE TITLE
Clearing cache with multiple tags

### ISSUE THREAD

**Issue by LrMiLoef** [nuwave/lighthouse#2242] opened 2022-11-29 08:17 UTC
Hi,

i'm using tagged caching in some of my GraphQL-Queries. it works fine so far. Now i don't know how to handle clearCache when it's needed to clear cache by multiple tags. 

For example:

type definition of meal:
```
type Meal {
    id: ID!
    title: String
    description: String
    calories: String
    category: [Category]
}

```
queries:
`meals(term: String): [Meal] @cache`
`categories: [Categories] @cache`

To invalidate multiple cache-tags id tried to do something like that:

mutation:
```
updateCategory(input: UpdateCategoryInput!): Boolean 
    @clearCache(type: "Query", field: "categories")
    @clearCache(type: "Query", field: "meals")
```

But this is not working. I'll get an error.

**Comment by spawnia** [comment] 2022-11-29 11:21
> But this is not working. I'll get an error.

How is it not working? What error are you getting?

**Comment by spawnia** [comment] 2023-08-09 08:38
Closing due to lack of reproducibility.

**Closed by spawnia** 2023-08-09 08:38 UTC
Labels: needs reproduction
