### ISSUE TITLE
@can directive is incomplete?

### ISSUE THREAD

**Issue by webard** [nuwave/lighthouse#912] opened 2019-08-12 14:50 UTC
**Describe the bug**
As You know @can directive can check if user have permission to do something cooperating with Model Policy and/or libraries like spatie/laravel-permission. It is okey, we can permit user to use query/mutation, but we cannot permit access to data, which query returns.

For example, we have query to fetch blog posts, which can be published or draft:
```
type Query {
getPosts: [Post!] @can(ability:"view") @all 
}
```
but types of queried data are three and depends on privileges:
- published posts can be viewed by everyone
- unpublished posts can be viewed by superAdmin
- unpublished (draft) posts can be viewed by it's author
Now it is impossible, because Policy does not check access in Post AND User context, only in User context. User can view everything or nothing.

Of course we can make three diffrent queries:
```
type Query {
getAllPosts: [Post!] @can(ability:"view all posts") @all 
getOwnPosts: [Post!] @can(ability:"view own posts") @all(scopes:["own"])
getPublicPosts: [Post!] @all(scopes:["public"])
}
```
but what about relations? Let's say Blog Post have comments, and comments can be hidden by moderator, comments can be drafted by author and comments can be published. So, we have two ways:
```
type Post {
id: ID!
comments: [Comment!] @can(ability:"view") @hasMany
}
```
which is **not work now**, and:
```
type Post {
id: ID!
publicComments: [Comment!] @hasMany(scopes:["public"])
allComments: [Comment!] @can(ability:"view hidden comments") @hasMany
draftedComments: [Comment!] @can(ability:"view own comments") @hasMany(scopes:["own"])
}
```

Maybe it is good idea to have clear naming what we got in proper field, maybe not becouse of redundancy, but I think if Laravel has powerful feature like Model Policies which can be used like this:
```php
<?php
class PostPolicy
{
    public function view(User $user, Post $post)
    {
        if ($post->status == 1) {
            return true;
        }

        // guest cannot view unpublished post
        if ($user === null) {
            return false;
        }

        // user with proper privileges can view unpublished post
        if ($user->can('view all posts')) {
            return true;
        }

        // authors can view their own unpublished posts
        if ($user->can('get own posts') && $user->id === $post->user_id) {
            return true;
        }

        return false;
    }
}
```

same should be possible with Lighthouse. I'm not sure if this is a bug, maybe it is idea for new directive like @policy(check:"view") which filter data we don't have permission to, from lists returned by queries? Let's discuss.

**Environment**
Lighthouse Version: 4.0-beta.2
Laravel Version: 5.8

**Comment by spawnia** [comment] 2019-08-13 20:23
The `@can` directive works as intended, it always runs before the actual field resolver. Laravel policies are generally not meant for filtering.

What you are suggesting is a new feature. You can implement a directive to filter your results quite easily using a [FieldMiddleware](https://lighthouse-php.com/master/custom-directives/field-directives.html#fieldmiddleware).

If you come up with a generalized and elegant solution that preferrably lines up with an existing concept from Laravel, we can discuss inclusion in this library.

I think that Lighthouse has sufficient primitives so you can implement what you need, so i am closing this issue for now.

**Closed by spawnia** 2019-08-13 20:23 UTC
